### PR TITLE
Xcode project maintenance

### PR DESCRIPTION
**Pull request by MaddTheSane**
* Fix the docs name.
* Bring back InfoPlist.strings.
* Better reverse-DNS name for the bundle identifier.
* Have the Xcode groups point to the project's directory structure.
* Add src/macosx/M6502.ins to the git ignore file.
* Add the Atari cartridge file type to the InfoPlist.strings file.

### CODE REVIEW

**Comment by sa666666** [comment]
I am willing to accept this if you leave the name as 'Stella-emu' instead of net.sourceforge.Stella.  Stella has been moved to github, and the name change was intentional.  As I said, the rest of the patch is fine, just not that part.

**Comment by MaddTheSane** [comment]
But 'Stella-emu' doesn't follow the reverse DNS used by Mac OS X apps. Perhaps using `com.github.stella-emu.stella`?

**Comment by sa666666** [comment]
The issue is that Stella may move again to another website, and I don't want the location of the project settings to change **again**.  I've looked at the recommendations from Apple, and having the name in reverse DNS is a suggestion (a should, not a must).  So I want to keep the name as-is.  The rest of your patch is fine; please re-submit it with name left alone.

**Comment by MaddTheSane** [comment]
Will do.
On Jun 4, 2017, at 1:40 PM, sa666666 <notifications@github.com<mailto:notifications@github.com>> wrote:


The issue is that Stella may move again to another website, and I don't want the location of the project settings to change again. I've looked at the recommendations from Apple, and having the name in reverse DNS is a suggestion (a should, not a must). So I want to keep the name as-is. The rest of your patch is fine; please re-submit it with name left alone.

**Pull request closed without merging**
