### PR TITLE
libretro: add achievements

### PR DESCRIPTION
**Pull request by trinemark**
http://retroachievements.org/gameList.php?c=25

### CODE REVIEW

**Comment by trinemark** [comment]
Note that I had to add to main core:
emucore/M6532.hxx

**Comment by sa666666** [comment]
Please change the signature to be const-correct: `uInt8* getRAM() const`.  Then I can accept it.

Also, on a side note, this will only work for scanning system RAM.  Many carts have RAM of their own that won't be covered by this case.

**Comment by sa666666** [comment]
I just realized that you might want to use this as a mutator, in which case `const` won't be appropriate.

Stella also has built-in cheat facilities, and it doesn't need such a method.  Basically, if you do `System::peek()` on the range $80 - $FF, you get full access to `M6532` RAM.  Similarly, if you want to change the RAM, use `System::poke()` on the same range instead.  Perhaps this is better than accessing the array directly??

**Comment by trinemark** [comment]
Unfortunately the libreto API wants a void *

```
void *retro_get_memory_data(unsigned id)
{
  switch (id)
  {
    case RETRO_MEMORY_SYSTEM_RAM:
      return stella.getRAM();

    default:
      return NULL;
  }
}
```

Retroarch has its own cheat engine searcher and modifier. But I'm stuck with the API. Let's ask RA dev @hizzlekizzle if there's anything else that can be done.

Kinda why I skirted this from the initial libretro commit.

**Comment by sa666666** [comment]
Well, not that it would be terribly efficient, but you could always create a local array, fill it will calls to `System::peek`, then return _that_ array.  That might be too costly, though.

For now (and until a better option comes up), I'd be willing to accept this if you wrap the method in `M6532` inside an include guard for libretro.  That way at least other ports won't start using it too.

**Comment by trinemark** [comment]
I'm not thrilled about it either. Your alternate idea is cool but I guess the overhead of:
```
run
- 128 poke non-inline calls
- stella emulate
- 128 peek non-inline calls
```

I accidentally did something similar in Beetle PCE (call get user setting at the start of a core drawing function that dropped 500 to 350 fps; it was a really large if-else block).

A batch call maybe would help cut it down.

**Comment by DirtyHairy** [comment]
If you made it `const uInt*`, you could just memcpy the 128 bytes every frame. I don't think this would have noticable performance impact.

**Comment by trinemark** [comment]
That's a simple idea. It would take out 1/2 of the problem (peek). :)

I'd have to poke 128 times, since the RA frontend cheat engine is likely to start freezing some values and other weird stuff it can do.

**Pull request merged**
