### PR TITLE
use gui flag

### PR DESCRIPTION
**Pull request by funbars**
for libretro port

### CODE REVIEW

**Comment by orbea** [comment]
Just curious, what is the current progress on this? It does seem like a good idea to only compile code when its needed. :)

**Comment by sa666666** [comment]
I'm not sure I will be accepting this one.  The UI code is integrated into Stella at a low level, and I don't want to fill the codebase with a bunch of `#ifdef's`.  If you don't use the UI, then it being compiled into the app is of no consequence.  Other than binary size, which is irrelevant for all hardware where Stella 6 is expected to run.   We have Stella running (successfully) on a 128MB system, and if the UI isn't causing code bloat issues there, then I don't think we need to worry about it elsewhere.

**Comment by sa666666** [comment]
I will add, unless there is a fairly non-invasive way of excluding the UI code, then I won't be doing it.

**Comment by sa666666** [comment]
I'm going to close this PR, since I've done a little experimentation, and I see that this can easily be accomplished.  So I will continue with this myself.  I want to handle it, since it won't be for just the libretro port, but integrated into the mainline code too.

**Comment by funbars** [comment]
Thank you, authors doing directly is best solution. I kept as draft to start discussion but didn't want merged.

**Pull request closed without merging**
