### PR TITLE
add libretro port

### PR DESCRIPTION
**Pull request by trinemark**

### CODE REVIEW

**Comment by trinemark** [comment]
Removed dupe Serializer files, changed Android to c++_static. Afterwards, everything is okay again.

Makefile I couldn't cleanup without messing it up, so (harmless) warnings left in.

Continue:
https://github.com/stella-emu/stella/pull/426

**Comment by sa666666** [comment]
I cam going to test and merge this soon.  Finishing up end-of-semester exams and marking here for about a week or so.  Then I will have time to look into this.  There is minimal changes to the core, so I see no problems with it being merged.

**Comment by trinemark** [comment]
The downtime was nice as it gave me a chance to port another libretro core (Mednafen PCE Accurate). Although now I'm thoroughly expended and looking to reduce github time for awhile.

**Comment by JesseFarebro** [comment]
For the definition of `__LIB_RETRO__` maybe something more generic like `BSPF_HEADLESS` could be used. I have a use case for a headless build of Stella that wouldn't use libretro. Maybe a lot of these pieces should be abstracted out to have a target for a headless Stella and libretro can build upon that?

Thoughts @sa666666 ?

**Comment by sa666666** [comment]
There is definitely room for further abstraction.  But as @trinemark says, we're not going to get much more development on this until it goes into mainline.  Personally, I want to abstract the zlib and png dependencies, so that we don't need dummy header files for this port.  But I have to pull this soon, since we have other changes to make elsewhere that will invalidate this PR.  Feel free to make suggestions (or create another PR) when I get this one integrated.

**Comment by sa666666** [comment]
OK, this is now committed.  I had to fix a few minor issues with code that has changed since the PR was made, but it's all fine now.  Please continue to work on this, and hopefully we can get it into RetroArch soon.

**Comment by trinemark** [comment]
Oh, cool. I'll try adding some more libretro features once PC Engine port is in better shape.

**Pull request merged**
