### PR TITLE
libretro: genesis controller

### PR DESCRIPTION
**Pull request by funbars**
Stay Frosty 2

### CODE REVIEW

**Comment by thrust26** [comment]
What's the problem here? Does libretto not support the 2nd button? Or is the game controller detection the problem.

The latter can be fixed by updating the controller in the game properties. 

The reason is an auto-detection clash. SF2 contains Genesis controller code. Stella checks for Genesis code and detects the Genesis as supported controller. Due to that SF2 detects that a Genesis controller is attached even if it is not. 

The same problem might affect other games which try to detect attached controllers themselves.

**Comment by funbars** [comment]
libretro does not support 2nd button.

**Comment by funbars** [comment]
pr connects libretro joypad to stella genesis. currently missing button 2, making game unplayable.

**Comment by sa666666** [comment]
If the game is unplayable using the Genesis controller, then its properties should be updated.  I can get to that, but that's a separate issue.

The code here should be to send the button action to the appropriate event.  I don't understand what you mean by "_libretro does not support 2nd button_".  Are you saying it's impossible for libretro to have more than one fire button?  Because I think that's not true.  And if libretro _can_ have more than one button, then it should be sending one for one of the Fire events, and the other for the other Fire events.  The fact that 'Stay Frosty' is not working needs to be fixed at a different level.

**Comment by funbars** [comment]
Omega Race works; libretro sends 3 buttons (BoosterGrip) to emucore.

Libretro currently only sends 1 button (Genesis) to emucore. With pr, libretro sends 2 buttons (Genesis) to emucore.

master Libretro does this for Genesis:
```
    default:
      EVENT(Event::JoystickZeroUp, input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_UP));
      EVENT(Event::JoystickZeroDown, input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_DOWN));
      EVENT(Event::JoystickZeroLeft, input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_LEFT));
      EVENT(Event::JoystickZeroRight, input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_RIGHT));
      EVENT(Event::JoystickZeroFire, input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_B));
break;
```

new pr does this for Genesis:
```
    case Controller::Type::Genesis:
      EVENT(Event::JoystickZeroFire5, input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_A));
      EVENT(Event::JoystickZeroUp, input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_UP));
      EVENT(Event::JoystickZeroDown, input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_DOWN));
      EVENT(Event::JoystickZeroLeft, input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_LEFT));
      EVENT(Event::JoystickZeroRight, input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_RIGHT));
      EVENT(Event::JoystickZeroFire, input_state_cb(0, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_B));
break;
```

**Comment by funbars** [comment]
Current Genesis:
- A = fire1

New Genesis:
- A = fire1
- B = fire2

**Comment by funbars** [comment]
(currently) Genesis controller will not correctly for any game, if 2 buttons needed.

edit: Don't anymore. Let someone else complain and post fix for broken libretro Genesis controllers.

**Pull request closed without merging**
