### PR TITLE
Run the build GHA on pushes as well as PRs

### PR DESCRIPTION
**Pull request by skitt**
This ensures that commits get a checkmark if they pass all tests.

Signed-off-by: Stephen Kitt <steve@sk2.org>

### CODE REVIEW

**Comment by sa666666** [comment]
@skitt, do you know if it's possible to be auto-notified if any of these automatic builds fail?  Perhaps by sending to an email address, or some other way?

**Comment by thrust26** [comment]
@skitt I think we figured out the notifications. Not perfect, does the main job nevertheless.

But we noticed several warnings regarding the build process (deprecated stuff). Can you fix that?

**Comment by skitt** [comment]
> @skitt I think we figured out the notifications. Not perfect, does the main job nevertheless.

Right, it’s not ideal — GHAs that produce warnings or errors work well in the context of a pull request, not so much on commits which are pushed directly.

> But we noticed several warnings regarding the build process (deprecated stuff). Can you fix that?

Are you referring to the

    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

warnings? I’ll take care of that.

**Comment by thrust26** [comment]
These warnings:

- _The_ `set-output` _command is deprecated and will be disabled soon._
- _The_ `save-state` _command is deprecated and will be disabled soon._

_Please upgrade to using Environment Files._

**Comment by thrust26** [comment]
> Right, it’s not ideal — GHAs that produce warnings or errors work well in the context of a pull request, not so much on commits which are pushed directly.

Also you only get informed if a build fails, but not if it got fixed. IMO a state **change** would be better, than only reporting failed builds. But I suppose that's no option here.

**Comment by skitt** [comment]
> These warnings:
> 
>     * _The_ `set-output` _command is deprecated and will be disabled soon._
> 
>     * _The_ `save-state` _command is deprecated and will be disabled soon._
> 
> 
> _Please upgrade to using Environment Files._

Ah right, see https://github.com/stella-emu/stella/pull/939; I’ll push another PR later to add Dependabot configuration so we get automated PRs when upgrades are available.

**Comment by skitt** [comment]
> Also you only get informed if a build fails, but not if it got fixed. IMO a state **change** would be better, than only reporting failed builds. But I suppose that's no option here.

On GitHub the general idea which drives a lot of GHA-based features is that changes are made through PRs, and failing PRs aren’t supposed to be merged — so the assumption is that your build should never go from not-building to building because the main branch should always build (at least, when each commit was made). I’m not saying this project should change its practices, just explaining some of the apparent shortcomings.

**Comment by thrust26** [comment]
It wasn't a PR, but a regular commit. Or does that mean the same in this case?

**Comment by skitt** [comment]
> It wasn't a PR, but a regular commit. Or does that mean the same in this case?

They’re not the same, which is the crux of the issue. In “GitHub theory”, all changes go through PRs, and jobs triggered on PRs are shown in the PR (as seen _e.g._ on https://github.com/stella-emu/stella/pull/939). Any job failure is then supposed to be investigated and ideally fixed as part of the PR (projects can be configured so that GitHub itself enforces this; see for example one of the projects I manage as part of my day job, https://github.com/submariner-io/submariner-operator/pulls, where all PRs have a list of jobs, some of which are marked “Required” and must pass for the PR to be mergeable). The resulting assumption is that the main branch is always “clean”, because changes aren’t merged into it if they break anything.

Regular commits which are pushed to the main branch trigger the jobs too (because they are configured to do so), but there’s not the same kind of context for notifications.

**Comment by thrust26** [comment]
OK, got you. Maybe we should switch our process.

@sa666666 What do you think?

**Pull request merged**
