### PR TITLE
libretro: fix msvc makefile

### PR DESCRIPTION
**Pull request by trinemark**

### CODE REVIEW

**Comment by orbea** [comment]
You probably don't want to remove all of these from msvc? Keeping `-Wall` would be good and you probably need `-std=c++14`?

**Comment by orbea** [comment]
I'm not sure I am understanding the issue correctly, but just moving `-Wextra` out of those might work.

**Comment by sa666666** [comment]
I agree.  Removing warnings won't necessarily make stuff compile, it will just error out later in the build.  We _need_ C++14 support, so removing that option will just mean the build fails when it gets to the first `make_unique` or something.  And some of the other ones will give a lot of warnings unless they're kept there.

I suggest removing only `extra` for now, and then work backwards to see what else needs to be removed.

**Comment by sa666666** [comment]
I accepted the other PR for now, since it only disabled `Wextra`, and perhaps that is sufficient.

**Comment by trinemark** [comment]
You will need to remove nearly all of them.
```
   CXXFLAGS+= -Wextra -Wno-unused-parameter -Wno-ignored-qualifiers
   CXXFLAGS+= -Wno-multichar -Wunused -Woverloaded-virtual -Wnon-virtual-dtor
```

No one is going to like how many errors msvc prints out now.

**Comment by sa666666** [comment]
You shouldn't remove the `-Wno-...` options, since those are turning _off_ warnings.  But you can try removing the other ones, which turn _on_ warnings.

**Pull request closed without merging**
