### PR TITLE
libretro port

### PR DESCRIPTION
**Pull request by trinemark**

### CODE REVIEW

**Comment by sa666666** [comment]
It seems there's still a `Serializer` class in `src/libretro` that's not needed; it can use the mainline one directly.

Also, not sure why the png and zlib headers are there, but essentially gutted.  Maybe we can work around this in the core, and remove it entirely.    What happens in libretro when a ROM is zipped?  How do you unzip it??

**Comment by trinemark** [comment]
```
It seems there's still a Serializer class in src/libretro that's not needed; it can use the mainline one directly.
```
That's my lame mistake; it wasn't there in @stellarporter's fork. I'll correct this in a new pr later later.

```
Also, not sure why the png and zlib headers are there, but essentially gutted. Maybe we can work around this in the core, and remove it entirely.
```
I'm assuming my predecessors shared the same experience - couldn't find an elegant way to decouple the GUI files without breaking the deck.

PNGLibrary.cxx has the png.h dependency.
FSNodeZIP.cxx has the zlib.h link.

Android was being very stubborn about the png library. I honestly am not too sure about the zlib one although it was conflicting with png earlier. Since frontend seems to handle zips, I just chucked it.

```
What happens in libretro when a ROM is zipped? How do you unzip it??
```
AFAIK, the frontend Retroarch checks the zip contents first for any known A2600 roms, unzips the selected game, and then streams a memory copy over to the libretro core. Although I notice now that roms usually in bin format.

Maybe the RA devs (@hizzlekizzle, @twinaphex, @fr500) can comment more. I'm not that knowledgeable on the frontend mechanics.

**Comment by hizzlekizzle** [comment]
There are cores that load zips directly (like MAME and FBA) but usually the user browses into the archive, selects the file to load, then the frontend unzips it to a temporary location and cleans up on exit. So yeah, tl;dr: frontend handles it.

**Comment by sa666666** [comment]
Well, it's good to know, since the PNG stuff at least can be refactored to be compiled out (it used to work that way in previous versions).  zlib is more low-level, but I think that can be handled too.

Mostly all of this is because zlib and png are available everywhere Stella is up to this point.  But it would be nice to not make any assumptions.  I will consider refactoring those out into conditionally-compiled components.

Other than that (and the `Serializer` fix), it's looking good so far.  I would want to try it all out before doing the pull, though.  Any advice on setting up a libretro environment, and using this build??

**Comment by trinemark** [comment]
Yeah, I think having others do some QA testing would make lots of sense. It is a new branch of Stella.

If it was me doing the actual merge commit, I wouldn't want some pathetic shifty error to slip into mainstream that easily.

```
1. Download a frontend:
https://www.retroarch.com/index.php?page=platforms
https://www.retroarch.com/index.php?page=linux-instructions

I would run it first and exit so it sets up everything.


2. Compiling core:
If it's msvc, you can just run the libretro vcxproj. Everyone else should:

cd src/libretro && make -f Makefile platform=%name%


platform:
windows_msvc2017_desktop_x64, windows_msvc2017_desktop_x86
unix
emscripten (web browser = https://github.com/libretro/RetroArch/tree/master/pkg/emscripten)
osx (untested)
???


android building:
cd src/libretro/jni && ndk-build

You'll see a cores folder which is where we place our dll, so, *.


3. Run retroarch again
- load core. select Atari - 2600 (Stella)
- load content. browse to rom. I use unzipped roms. I chose H.E.R.O.
- select Stella core again if prompted.
- on my (default?) setup: enter = start, shift = select, s = button.
```

**Comment by trinemark** [comment]
Yeah, I think having others do some QA testing would make lots of sense. It is a new branch of Stella.

If it was me doing the actual merge commit, I wouldn't want some pathetic shifty error to slip into mainstream that easily.

```
1. Download a frontend:
https://www.retroarch.com/index.php?page=platforms
https://www.retroarch.com/index.php?page=linux-instructions

I would run it first and exit so it sets up everything.


2. Compiling core:
If it's msvc, you can just run the libretro vcxproj. Everyone else should:

cd src/libretro && make -f Makefile platform=%name%


platform:
windows_msvc2017_desktop_x64, windows_msvc2017_desktop_x86
unix
emscripten (web browser = https://github.com/libretro/RetroArch/tree/master/pkg/emscripten)
osx (untested)
???


android building:
cd src/libretro/jni && ndk-build

You'll see a cores folder which is where we place our dll, so, *.


3. Run retroarch again
- load core. select Atari - 2600 (Stella)
- load content. browse to rom. I use unzipped roms. I chose H.E.R.O.
- select Stella core again if prompted.
- on my (default?) setup: enter = start, shift = select, s = button.
```

edit: Deleted those 2 libretro/Serializer files. They were dead weight and not even being compiled.

**Comment by orbea** [comment]
> Any advice on setting up a libretro environment, and using this build??

With RetroArch its essentially cloning the repo and doing `./configure && make`. You can use `./configure --help` to see options and you can should be able to start the core with `./retroarch -L /path/to/stella_libretro.so /path/to/rom`. You can also start content from the menu.

Its possible that there could be any number of other libretro frontends which would work, but currently RetroArch seems to be the most viable.

**Comment by sa666666** [comment]
I will try to find time this week to at least test this out and make sure it all compiles.  If you can fix the redundant `Serializer` class, and the code compiles, I am willing to accept the pull request.

**Comment by trinemark** [comment]
Okay. I'll do another rebase first to be safe and then send another clean PR.

**Pull request closed without merging**
