### PR TITLE
Add debugger commands to manipulate controller state.

### PR DESCRIPTION
**Pull request by uhrm**
This pull request adds 10 new debugger commands to manipulate programmatically the state of the controller inputs. These commands are supposed to be used from debugger scripts (using `exec`). The names of the commands are similar to the built-in debugger functions.

### CODE REVIEW

**Comment by sa666666** [comment]
Thanks for the contribution.  Before I commit it, I would prefer if you change all calls to ```Controller::void set(DigitalPin pin, bool value);``` to actually take a boolean as the second argument.  You tend to use 0 and 1, and while the compiler can do the conversion, I would prefer the calls to clearly indicate a C++ bool vs. a C-style bool.

**Comment by sa666666** [comment]
In addition to my last message, please rebase and fix conflicts before I merge your stuff.

**Comment by uhrm** [comment]
Alright, I finally found some time to implement the changes and rebase onto master.

This pull request was supposed to be only for the first commit of this branch (https://github.com/stella-emu/stella/pull/253/commits/eaa41e0366e5fefa336139227f3ac12b7bbd90f2). I didn't know that it would show all commits in the branch. Anyways, feel free to apply as far as you want.

**Comment by thrust26** [comment]
@uhrm Can you document your changes in DebuggerParser help, please?

E.g. dump now takes 3 arguments, maybe more is missing, not sure.

**Pull request merged**
