### PR TITLE
Add a GitHub action to build on Windows

### PR DESCRIPTION
**Pull request by skitt**
This reproduces the Appveyor build for 32- and 64-bit Windows.

Signed-off-by: Stephen Kitt <steve@sk2.org>

### CODE REVIEW

**Comment by sa666666** [comment]
I wonder, do we need this one, since we already have Appveyor doing it?  I suppose the only thing wasted is compute time on the servers.

**Comment by sa666666** [comment]
Well, at least you will get notification of Linux breaking, so I think it would be very useful.  It still won't detect issues with Retroarch builds, but they have their own CI system for that.

**Comment by sa666666** [comment]
I see GHA is faster for the Windows builds than Appveyor.  Perhaps we should just discontinue the Appveyor tests?  I still need to figure out how to do that, of course.

**Comment by skitt** [comment]
> I wonder, do we need this one, since we already have Appveyor doing it? I suppose the only thing wasted is compute time on the servers.

I was thinking we could drop the AppVeyor builds ;-).

**Comment by sa666666** [comment]
OK, I've dropped the Appveyor stuff.  But now I guess I need to configure Github to automatically run these tests on each commit.  And somehow post a little icon or something next to the commit ID telling if it succeeded or failed.  That's what Appveyor used to do.  How would I proceed with this?

**Comment by skitt** [comment]
> OK, I've dropped the Appveyor stuff. But now I guess I need to configure Github to automatically run these tests on each commit? And somehow post a little icon or something next to the commit ID telling if it succeeded or failed. That's what Appveyor used to do. How would I proceed with this?

https://github.com/stella-emu/stella/pull/937 will do that, see https://github.com/skitt/stella/commits/gaw2 for the checkmark on the last commit.

**Pull request merged**
