### PR TITLE
CDFJ+ bankswitching

### PR DESCRIPTION
**Pull request by chrisdwalton**
Add support for CDFJ+ bankswitching (refactored based on comments from Thomas)

### CODE REVIEW

**Comment by sa666666** [comment]
@thrust26 seems to be taking the lead on this, so I will ask him to critique this PR too.

**Comment by thrust26** [comment]
@chrisdwalton Can you please also update the initial description in `CartCDF.hxx`?

Also: Can CDF(J)(+) ROM sizes be only a power of 2?

**Comment by sa666666** [comment]
Also, can you provide some test ROMs that we can include in the repo, to test this going forward?

**Comment by DirtyHairy** [comment]
Yes, a test ROM would be nice, then I'll port over the changes to 6502.ts

**Comment by chrisdwalton** [comment]
Thanks - I have created another pull request with the updated header and test binaries.

**Pull request merged**
