### PR TITLE
Suggested layout changes for the Launcher UI.

### PR DESCRIPTION
**Pull request by splendidnut**
As mentioned in [ UI Suggestion -> Different layout for new Launcher #906 ](https://github.com/stella-emu/stella/issues/906), I've changed the layout in the new Launcher UI to have the controls in a more natural order:

- The positions of the filter widget and the path widget have been swamped.
- The reload button is now with the other navigation buttons.
- The Options button has been moved to the far right (which is somewhat more consistent with the debugger).

image

### CODE REVIEW

**Comment by thrust26** [comment]
Hm, there are things I like and things I do not like.

> The positions of the filter widget and the path widget have been swamped.

100% agreed here 

> The reload button is now with the other navigation buttons.

This I do not like, IMO it more belongs to filtering (can't exactly tell you why) and also, because the navigation widget is also used for selecting directories and saving files (check them out, please). There a reload button IMO makes little sense. 

> The Options button has been moved to the far right (which is somewhat more consistent with the debugger).

Yes and no. 

- Yes, it is more consistent with the debugger. But for the normal user, this is quite irrelevant. 
- No, because also for consistency the Help button should always be top left.
- No, because it eats valuable space from the path display. The launcher can be set pretty narrow and the paths can become pretty long.

So I would prefer the Options and Reload buttons in the 2nd row, the Help button at the top right.

**Comment by splendidnut** [comment]
Choosing a location for the reload button was a bit tricky.  I debated on where to stick it and chose the navigation/path widget line partially due to the use of that location in web-browsers.

The main purpose of the Reload button seems like a way to make up for the lack of a nice cross-platform way of detecting filesystem changes from the OS.  If that is so, then the reload button is generally useful whenever you have a view of the filesystem (whether it's for loading/saving, or just selecting directories).  So, it would make more sense to have it in the widget that is most likely available in all those cases.

I can stand behind wanting to have as much space as possible for the Navigation/ Path Widget... but at the same time, if space is that much of an issue, I would toss out most of the navigation buttons (all except home) and replace with a dropdown favorites list or recent paths that ROMs were played from.  :)

With all that said, I'm fine with moving the Reload button down into the filtering widget line.  It really can exist in either line being as they all affect the file/directory display.

With the other buttons,  I'm fine with locating the help button in the upper right and the options button below it... these are the only two things that are not really part of the file display so should be separated out on the right.

I've been playing around with (and fighting) the layout stuff all morning, so nothing is committed, but this is what I've gotten so far:

image

I still want to align the end of the filter field (+ icons) to fit nicely above the list of files.... which should allow more space between the files count and the Options button.

**Comment by thrust26** [comment]
That's better. How about moving the Reload button at the very left of the 2nd line?

**Comment by splendidnut** [comment]
Yeah, the filter may not be able to be aligned.  I just shrunk the launcher as small as allowed (640x480.) and it looks like the Options button should probably shrink at that point (and I need to fix the file count text to also use the smaller version):

image


Yeah, I can update screenshots when I'm done... I see 4:
- launcher.png
- rominfo_1x_large.png
- rominfo_1x_small.png
- rominfo_2x_small.png

Did I miss any?

**Comment by thrust26** [comment]
> ...it looks like the Options button should probably shrink at that point (and I need to fix the file count text to also use the smaller version):

IMO not required. A small search field is fine, people usually only enter very few letters here. 

> Did I miss any?

Nope. Just make sure that you do not display confidential info.

**Comment by thrust26** [comment]
oops

**Comment by thrust26** [comment]
I am missing the Favorites directory in the screenshots. Just mark any file or directory and restart.

**Comment by splendidnut** [comment]
Yeah, I forgot to do a pull locally before the commit and push... I did it afterwards on my fork in Github and the pull request auto-updated with that.

I can redo the screenshots with the favorites directory shown.

**Review by thrust26 — APPROVED** [review]

**Pull request merged**
