### PR TITLE
Feature moviecart

### PR DESCRIPTION
**Pull request by lodefmode**
Initial implementation of Movie Cart.
Branch name is feature-moviecart

a92a33b4da2d1d1018507011ea2fa0d2b090e9b9   Basic Support
44e15ff86f680639ce324a0d0ce8e598568b12ef  Limit size of ROM image if file appears to be MVC

Two .mvc files can be found in:

https://github.com/lodefmode/moviecart/tree/main/output/colorizer

### CODE REVIEW

**Comment by lodefmode** [comment]
Looking at the file sizes, I went ahead and moved everything into CartMVC, getting rid of the MovieCart subfolder.
This seems more innocuous.
438bd2f5beb1f3b784fd

**Comment by sa666666** [comment]
I'm working on this now, for release in Stella 6.6.  I've pulled to a branch in Stella, but I'm not sure how to remove this PR now.  The code is now in Stella, but not (yet) in master.

**Comment by lodefmode** [comment]
> I'm working on this now, for release in Stella 6.6. I've pulled to a branch in Stella, but I'm not sure how to remove this PR now. The code is now in Stella, but not (yet) in master.

Wow thats great.  I just now finished implementing Thomas Jentzsch's improvements to get rid of two mis-colored columns.

**Comment by sa666666** [comment]
I now have this fully integrated in a branch in Stella, so I will go ahead and close this PR.  I changed some stuff around to match Stella code style, eliminated redundant code where Stella already had the same functionality, etc.  Hope you don't mind me making the changes.

If you have anything further to commit, please check out from the branch I've created, and base all your new code on that.

Thanks again!

**Comment by lodefmode** [comment]
Perfect thank you very much!

**Comment by thrust26** [comment]
Any chance for more movie ROMs made available?

**Comment by lodefmode** [comment]
Yah absolutely.  Open to suggestions for content.  A 10 second clip is about 2.5 MB.

**Comment by thrust26** [comment]
Cool, try to play with encoding will be fun.

Content? Anything legal that works well. Size shouldn't be a major problem. 
How about [this](https://www.youtube.com/watch?v=jmF0edcnw4w)? Or something similar.

**Comment by lodefmode** [comment]
Okay I've added a few to my repo: moviecart/output/colorizer
Would you prefer I add them as bins to the stella testroms , and create a pull request?

**Comment by thrust26** [comment]
I will add them. Thanks for sharing!

**Pull request closed without merging**
