### PR TITLE
[libretro] Update libretro.h

### PR DESCRIPTION
**Pull request by keithbowes**

### CODE REVIEW

**Comment by thrust26** [comment]
What did you change here? Looks like the whole file got replaced.

**Comment by keithbowes** [comment]
I just copied the latest libretro.h from libretro-common.  I'm not sure why it replaces the whole file; I'm guessing different line endings.

It replacing the whole file is actually the reason I just added the necessary new bits instead of updating the file when I implemented input bitmasks, because if I had included the new libretro.h, it would have been the bulk of the changes in the diff.

The update will allow using new libretro features (persistent data buffers, for example) in the future.

**Comment by keithbowes** [comment]
I can change the line endings and do a force push if you'd like.

**Comment by thrust26** [comment]
Can you solve the conflicts first, please?

**Comment by keithbowes** [comment]
What conflicts?  I'm not getting anything on GitHub or command-line git.

**Pull request merged**
