### PR TITLE
64-bit ambiguity

### PR DESCRIPTION
**Pull request by funbars**

### CODE REVIEW

**Comment by funbars** [comment]
Vita and 3DS (gcc 7.1.0)

**Comment by sa666666** [comment]
What problem is this patch meant to solve?  If it's warnings, then I think this can be better accomplished by disabling the warning in the compiler.  We compile use gcc 7.1/32-bit elsewhere, and no issues come up.

**Comment by orbea** [comment]
I think this is trying to solve compile failure for the playstation vita?

**Comment by sa666666** [comment]
Sure, but _what_ is the failure?  Because there might be a less invasive way of fixing it than changing all that code.  Maybe it's something that we can pass to the compiler to fix it.

**Comment by funbars** [comment]
```
devkitpro/devkitPPC/bin/powerpc-eabi-g++ -I. -I.. -I../libretro -I../libretro/libretro-common/include -I../emucore -I../emucore/tia -I../common -I../common/audio -I../common/tv_filters -I../libretro/std   -std=c++14  -Wall -Wextra -Wno-unused-parameter -Wno-multichar -Wunused -fno-rtti -Woverloaded-virtual -Wnon-virtual-dtor -mcpu=750 -meabi -mhard-float -DBLARGG_BIG_ENDIAN=1 -D__ppc__ -U__INT32_TYPE__ -U __UINT32_TYPE__ -D__INT32_TYPE__=int -mwup -DWII -O3 -DNDEBUG -fomit-frame-pointer -Wall -W -Wno-unused-parameter  -D__LIB_RETRO__ -DSOUND_SUPPORT -DHAVE_STDINT_H -DHAVE_STRINGS_H -fno-rtti -pedantic -c -o../emucore/OSystem.o ../emucore/OSystem.cxx
../emucore/OSystem.cxx: In member function 'std::__cxx11::string OSystem::createConsole(const FilesystemNode&, const string&, bool)':
../emucore/OSystem.cxx:367:44: error: conversion from 'long int' to 'const Variant' is ambiguous
     mySettings->setValue("romloadcount", 0l);
                                            ^
In file included from ../emucore/Settings.hxx:23:0,
                 from ../emucore/OSystem.hxx:58,
                 from ../common/MediaFactory.hxx:26,
                 from ../emucore/OSystem.cxx:24:
../common/Variant.hxx:54:5: note: candidate: Variant::Variant(bool)
     Variant(bool b)   { buf().str(""); buf() << b; data = buf().str(); }
     ^~~~~~~
../common/Variant.hxx:53:5: note: candidate: Variant::Variant(double)
     Variant(double d) { buf().str(""); buf() << d; data = buf().str(); }
     ^~~~~~~
../common/Variant.hxx:52:5: note: candidate: Variant::Variant(float)
     Variant(float f)  { buf().str(""); buf() << f; data = buf().str(); }
     ^~~~~~~
../common/Variant.hxx:51:5: note: candidate: Variant::Variant(uInt32)
     Variant(uInt32 i) { buf().str(""); buf() << i; data = buf().str(); }
     ^~~~~~~
../common/Variant.hxx:50:5: note: candidate: Variant::Variant(Int32)
     Variant(Int32 i)  { buf().str(""); buf() << i; data = buf().str(); }
     ^~~~~~~
../common/Variant.hxx:48:5: note: candidate: Variant::Variant(const char*)
     Variant(const char* s) : data(s) { }
     ^~~~~~~
In file included from ../emucore/OSystem.hxx:58:0,
                 from ../common/MediaFactory.hxx:26,
                 from ../emucore/OSystem.cxx:24:
../emucore/Settings.hxx:91:10: note:   initializing argument 2 of 'void Settings::setValue(const string&, const Variant&, bool)'
     void setValue(const string& key, const Variant& value, bool persist = true);
          ^~~~~~~~
```

**Comment by funbars** [comment]
```
../emucore/CartDetector.cxx: In static member function 'static bool CartDetector::isProbablyMDM(const ByteBuffer&, uInt32)':
../emucore/CartDetector.cxx:947:58: error: no matching function for call to 'min(uInt32&, unsigned int)'
   return searchForBytes(image.get(), std::min(size, 8192u), mdmc, 4, 1);
                                                          ^
In file included from /devkitpro/devkitARM/arm-none-eabi/include/c++/7.1.0/algorithm:61:0,
                 from ../common/bspf.hxx:42,
                 from ../emucore/CartDetector.cxx:18:
/devkitpro/devkitARM/arm-none-eabi/include/c++/7.1.0/bits/stl_algobase.h:195:5: note: candidate: template<class _Tp> constexpr const _Tp& std::min(const _Tp&, const _Tp&)
     min(const _Tp& __a, const _Tp& __b)
     ^~~
/devkitpro/devkitARM/arm-none-eabi/include/c++/7.1.0/bits/stl_algobase.h:195:5: note:   template argument deduction/substitution failed:
../emucore/CartDetector.cxx:947:58: note:   deduced conflicting types for parameter 'const _Tp' ('long unsigned int' and 'unsigned int')
   return searchForBytes(image.get(), std::min(size, 8192u), mdmc, 4, 1);
                                                          ^
/devkitpro/devkitARM/arm-none-eabi/include/c++/7.1.0/algorithm:61:0,
                 from ../common/bspf.hxx:42,
                 from ../emucore/CartDetector.cxx:18:
/devkitpro/devkitARM/arm-none-eabi/include/c++/7.1.0/bits/stl_algobase.h:243:5: note: candidate: template<class _Tp, class _Compare> constexpr const _Tp& std::min(const _Tp&, const _Tp&, _Compare)
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^~~
/devkitpro/devkitARM/arm-none-eabi/include/c++/7.1.0/bits/stl_algobase.h:243:5: note:   template argument deduction/substitution failed:
../emucore/CartDetector.cxx:947:58: note:   deduced conflicting types for parameter 'const _Tp' ('long unsigned int' and 'unsigned int')
   return searchForBytes(image.get(), std::min(size, 8192u), mdmc, 4, 1);
                                                          ^
In file included from /devkitpro/devkitARM/arm-none-eabi/include/c++/7.1.0/algorithm:62:0,
                 from ../common/bspf.hxx:42,
                 from ../emucore/CartDetector.cxx:18:
/devkitpro/devkitARM/arm-none-eabi/include/c++/7.1.0/bits/stl_algo.h:3450:5: note: candidate: template<class _Tp> constexpr _Tp std::min(std::initializer_list<_Tp>)
     min(initializer_list<_Tp> __l)
     ^~~
/devkitpro/devkitARM/arm-none-eabi/include/c++/7.1.0/bits/stl_algo.h:3450:5: note:   template argument deduction/substitution failed:
../emucore/CartDetector.cxx:947:58: note:   mismatched types 'std::initializer_list<_Tp>' and 'long unsigned int'
   return searchForBytes(image.get(), std::min(size, 8192u), mdmc, 4, 1);
                                                          ^
In file included from /devkitpro/devkitARM/arm-none-eabi/include/c++/7.1.0/algorithm:62:0,
                 from ../common/bspf.hxx:42,
                 from ../emucore/CartDetector.cxx:18:
/devkitpro/devkitARM/arm-none-eabi/include/c++/7.1.0/bits/stl_algo.h:3456:5: note: candidate: template<class _Tp, class _Compare> constexpr _Tp std::min(std::initializer_list<_Tp>, _Compare)
     min(initializer_list<_Tp> __l, _Compare __comp)
     ^~~
/devkitpro/devkitARM/arm-none-eabi/include/c++/7.1.0/bits/stl_algo.h:3456:5: note:   template argument deduction/substitution failed:
../emucore/CartDetector.cxx:947:58: note:   mismatched types 'std::initializer_list<_Tp>' and 'long unsigned int'
   return searchForBytes(image.get(), std::min(size, 8192u), mdmc, 4, 1);
                                                          ^
Makefile:627: recipe for target '../emucore/CartDetector.o' failed
```

**Comment by sa666666** [comment]
I'm not convinced that changing the code in this way is the correct fix.  The same code compiles in 32 and 64-bit compilers on many different systems, so I'm wondering how this platform differs.

Also, have you tested Stella on this hardware to make sure it can run sufficiently?  If it can't, then I don't see the point in making any changes.

Finally, how are you compiling this?  I would like to try it myself, to see if it can be fixed with making invasive changes.

**Comment by funbars** [comment]
I do not have 3ds or vita hardware. Same errors.

Vita
https://github.com/stella-emu/stella/files/3135733/stella-vita.log

3ds toolset
https://github.com/libretro/libretro-toolchains/blob/master/3ds.tar.xz?raw=true

```
export DEVKITARM=$DIR/tools/devkitpro/devkitARM
export DEVKITPRO=$DIR/tools/devkitpro


cd src/libretro
make -f Makefile platform=ctr


# CTR (3DS)
else ifeq ($(platform), ctr)
   TARGET := $(TARGET_NAME)_libretro_$(platform).a
   CXX = $(DEVKITARM)/bin/arm-none-eabi-g++$(EXE_EXT)
   AR = $(DEVKITARM)/bin/arm-none-eabi-ar$(EXE_EXT)
   ENDIANNESS_DEFINES := -DLSB_FIRST
   FLAGS += -DARM11 -D_3DS
   FLAGS += -march=armv6k -mtune=mpcore -mfloat-abi=hard
   FLAGS += -mword-relocations
   FLAGS += -fomit-frame-pointer -fstrict-aliasing -ffast-math
   FLAGS += -fno-rtti
   FLAGS += -fno-exceptions -DDISABLE_EXCEPTIONS
   STATIC_LINKING = 1
   LOAD_FROM_MEMORY = 0
```

You will get mutex, thread error. Add https://github.com/stella-emu/stella/pull/464 to workaround. 3DS has link problems atm.

**Comment by sa666666** [comment]
I will not commit code that affect a large part of the codebase until I have been able to test it myself.  I didn't mind changing compiler flags and using the buildbot to test those changes, but not making large changes like this.  I will try to find some time to test this myself with devkitpro.

Also, for the systems that don't have threading support, I think we just need to say that they need to keep using the old (3.x) core instead.  Going forward, Stella will be making more use of C++11/14 features, and stubbing out that code because of obsolete/incorrect compilers will eventually fail.

**Comment by sa666666** [comment]
I think the platforms without threading support should stick to the old core.

It seems like Vita is treating `int` as not being 32-bit.  So we either have to tell the compiler to treat it as 32-bit, or also leave this platform for the old core.

**Pull request closed without merging**
